### ISSUE TITLE
i may be stupid

### ISSUE THREAD

**Issue by DewOnTheGrass** [Rarisma/Rarismas-Server-Manager#15]
I have no idea how to join the server that I have created. I have the available ports, but no IP. Could the app please tell the user the resultant IP for the server?

**Comment by Rarisma** [comment]
Just google what is my IP, however this will be fixed in a future version

**Comment by DewOnTheGrass** [comment]
gotcha! can the server-hosting computer also join the server that way?

**Comment by Rarisma** [comment]
yeah or on that computer you can use localhost
